// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionHub.Api.Data;

#nullable disable

namespace SessionHub.Api.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    partial class ConferenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SessionHub.Api.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("SessionHub.Api.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeakerId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This session walks through creating a small but realistic application from the ground up, covering architecture, APIs, UI, and demo-friendly decisions that make a conference talk easier to follow.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Grand Ballroom",
                            SpeakerId = 1,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Learn how a focused product idea becomes a polished app with clear architecture and pragmatic decisions.",
                            Title = "From Idea to Ship: Building a Modern Conference Planner",
                            Track = "Architecture"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This walkthrough covers contract design, resource modeling, and DTO choices that help teams move quickly without creating brittle surfaces.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Harbor 1",
                            SpeakerId = 2,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "A simple API design approach that keeps developers productive and services easy to evolve.",
                            Title = "Designing HTTP APIs That Stay Friendly to Teams",
                            Track = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This session highlights the practical patterns for using Entity Framework Core in a clean, readable app that feels realistic without becoming over-engineered.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 11, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "Cedar Hall",
                            SpeakerId = 3,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Use EF Core confidently for a small application with migrations, SQLite, and seed data.",
                            Title = "Entity Framework Core for Demo-Ready Apps",
                            Track = "Data"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Explore how a simple React view can effectively surface session data, speaker profiles, and browsing flows without extra complexity.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Innovation Lab",
                            SpeakerId = 4,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Build an interface that is easy to explain, fast to code, and pleasant to use.",
                            Title = "React Patterns for Conference Dashboards",
                            Track = "Frontend"
                        },
                        new
                        {
                            Id = 5,
                            Description = "See why a focused service layer can keep logic clean and make a demo app easier to reason about in front of an audience.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "Skyline 2",
                            SpeakerId = 5,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Keep business logic readable and testable in a small application architecture.",
                            Title = "Service Layers Without the Drama",
                            Track = "Architecture"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This session demonstrates how thoughtful API responses and user-friendly messaging improve every stage of an app.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "Harbor 2",
                            SpeakerId = 6,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 13, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Create API feedback that keeps users informed and developers confident.",
                            Title = "Building Trust with Better Error Handling",
                            Track = "Backend"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Learn how small improvements in the app stack create a more responsive experience for users who are browsing a busy conference schedule.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 15, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 2,
                            Room = "North Hall",
                            SpeakerId = 7,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 14, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Get fast wins with caching, response shaping, and layout choices.",
                            Title = "Performance Tuning for Real-World Web Apps",
                            Track = "Performance"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Use the SessionHub example to understand how sessions and speakers relate and how a small domain model supports a larger experience.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Cedar Hall",
                            SpeakerId = 8,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 14, 15, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Think through the essential entities behind a conference planner.",
                            Title = "Designing a Data Model for Event Discovery",
                            Track = "Data"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Learn how request and response models help frontend and backend teams collaborate effectively when building user-visible features.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Harbor 1",
                            SpeakerId = 2,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Good contracts are documentation, not just implementation details.",
                            Title = "API Contracts That Help Teams Communicate",
                            Track = "Backend"
                        },
                        new
                        {
                            Id = 10,
                            Description = "This talk explores how clean layout decisions, strong hierarchy, and clear content produce more usable software with less code.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Innovation Lab",
                            SpeakerId = 4,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Build interfaces that tell a story without distracting from the main action.",
                            Title = "Minimal UI, Maximum Clarity",
                            Track = "Frontend"
                        },
                        new
                        {
                            Id = 11,
                            Description = "This session covers the shared security design choices that matter most when shipping software quickly to customers.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 12, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "Skyline 2",
                            SpeakerId = 9,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 11, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Look at practical patterns that help keep applications safer without heavy process overhead.",
                            Title = "Secure by Default: Common Design Patterns",
                            Track = "Security"
                        },
                        new
                        {
                            Id = 12,
                            Description = "This talk shows how to evolve aging applications through clear boundaries, gradual changes, and careful modernization decisions.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 13, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 2,
                            Room = "Grand Ballroom",
                            SpeakerId = 10,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 12, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Use incremental patterns to improve existing systems with less risk.",
                            Title = "Modernizing Legacy Systems Without a Rewrite",
                            Track = "Architecture"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Learn tactics for making teams more effective through good tooling, straightforward automation, and smarter standards.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "North Hall",
                            SpeakerId = 7,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Small process improvements can create a huge impact for teams and outcomes.",
                            Title = "Developer Experience That Scales",
                            Track = "Platform"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Explore how product teams can interpret signals and behaviors into a simple experience that helps users discover what matters.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 15, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 0,
                            Room = "Harbor 2",
                            SpeakerId = 2,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Turn scattered information into a practical product story that users understand.",
                            Title = "From Data to Decision: Building Useful Insights",
                            Track = "Product"
                        },
                        new
                        {
                            Id = 15,
                            Description = "This session demonstrates how accessibility, usability, and maintainability all improve when we adopt simple design practices.",
                            EndTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 16, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Level = 1,
                            Room = "Innovation Lab",
                            SpeakerId = 8,
                            StartTimeUtc = new DateTimeOffset(new DateTime(2026, 9, 15, 15, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Summary = "Build inclusive experiences without making the work more complicated for the team.",
                            Title = "The Power of Accessible Interfaces",
                            Track = "UX"
                        });
                });

            modelBuilder.Entity("SessionHub.Api.Models.Speaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Maira helps teams grow modern cloud architectures and developer productivity across large organizations.",
                            Company = "Northwind Labs",
                            FirstName = "Maira",
                            LastName = "Lopez",
                            PhotoUrl = "https://images.unsplash.com/...",
                            Title = "Principal Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Daniel connects engineering decisions with product strategy and measurable outcomes for customer experience.",
                            Company = "Brightlane",
                            FirstName = "Daniel",
                            LastName = "Kemp",
                            PhotoUrl = "",
                            Title = "Director of Product"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Priya specializes in resilient distributed systems, event-driven platforms, and operational excellence.",
                            Company = "Contoso Cloud",
                            FirstName = "Priya",
                            LastName = "Nair",
                            PhotoUrl = "",
                            Title = "Cloud Architect"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Lance teaches developers how to build better user experiences with practical, production-friendly guidance.",
                            Company = "BluePeak",
                            FirstName = "Lance",
                            LastName = "Brooks",
                            PhotoUrl = "",
                            Title = "Developer Advocate"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Alicia enjoys turning complex systems into approachable patterns that teams can trust and evolve.",
                            Company = "Fabrikam",
                            FirstName = "Alicia",
                            LastName = "Stone",
                            PhotoUrl = "",
                            Title = "Staff Software Engineer"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Marco helps organizations turn AI ideas into useful workflows that deliver real business value.",
                            Company = "DataWorks",
                            FirstName = "Marco",
                            LastName = "Davis",
                            PhotoUrl = "",
                            Title = "AI Solutions Lead"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Harper focuses on developer platforms, automation, and reliable engineering practices for scaling teams.",
                            Company = "Quanta Systems",
                            FirstName = "Harper",
                            LastName = "Nguyen",
                            PhotoUrl = "",
                            Title = "Platform Engineer"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Ethan bridges design and implementation to create intuitive, accessible digital products.",
                            Company = "Pixel Harbor",
                            FirstName = "Ethan",
                            LastName = "Rossi",
                            PhotoUrl = "",
                            Title = "UX Engineer"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Sofia helps teams design secure systems without slowing delivery or sacrificing usability.",
                            Company = "Redline Security",
                            FirstName = "Sofia",
                            LastName = "Petrov",
                            PhotoUrl = "",
                            Title = "Security Architect"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Jordan works with teams to modernize legacy systems and improve delivery through better architecture.",
                            Company = "Northwind Consulting",
                            FirstName = "Jordan",
                            LastName = "Mills",
                            PhotoUrl = "",
                            Title = "Senior Consultant"
                        });
                });

            modelBuilder.Entity("SessionHub.Api.Models.Favorite", b =>
                {
                    b.HasOne("SessionHub.Api.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SessionHub.Api.Models.Session", b =>
                {
                    b.HasOne("SessionHub.Api.Models.Speaker", "Speaker")
                        .WithMany("Sessions")
                        .HasForeignKey("SpeakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("SessionHub.Api.Models.Speaker", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
